apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-consumer-check-greetings-reversed
  name: hello-world-consumer-check-greetings-reversed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-consumer-check-greetings-reversed
  template:
    metadata:
      labels:
        app: hello-world-consumer-check-greetings-reversed
    spec:
      containers:
      - name: hello-world-consumer
        image: strimzi/hello-world-consumer:latest
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: event-bus-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: sample-user-tls
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: sample-user-tls
                key: user.key
          - name: BOOTSTRAP_SERVERS
            value: event-bus-kafka-bootstrap:9093
          - name: TOPIC
            value: apps.samples.greetings.reversed
          - name: GROUP_ID
            value: sample-consumer-reversed-check-group
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
