apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSinkConnector # (1)
  tasksMax: 2
  config: # (2)
    file: "/tmp/my-file" # (3)
    topics: my-topic # (4)
