apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nagcloudlab-com
  namespace: kafka
spec:
  secretName: nagcloudlab-com-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  subject:
    organizations:
      - NagCloudLab
  commonName: nagcloudlab.com
  dnsNames:
    - nagcloudlab.com
    - www.nagcloudlab.com
    - kafka.nagcloudlab.com
    - broker-0.kafka.nagcloudlab.com
    - broker-1.kafka.nagcloudlab.com
    - broker-2.kafka.nagcloudlab.com
