apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.6.0
  replicas: 1
  connectCluster: "cluster-b" # Must be the target custer
  clusters:
    - alias: "cluster-a" # Source cluster
      bootstrapServers: kafka.nagcloudlab.com:443
      tls:
        trustedCertificates:
          - secretName: my-cluster-ca-cert
            certificate: ca.crt
    - alias: "cluster-b" # Target cluster
      bootstrapServers: 52.172.5.103:9093
      tls:
        trustedCertificates:
          - secretName: your-cluster-cluster-ca-cert
            certificate: ca.crt
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "cluster-a"
      targetCluster: "cluster-b"
      sourceConnector:
        tasksMax: 2
        config:
          # -1 means it will use the default replication factor configured in the broker
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: "false"
      checkpointConnector:
        tasksMax: 1
        config:
          checkpoints.topic.replication.factor: -1
      topicsPattern: ".*"
      groupsPattern: ".*"
